name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        node-version: ['10', '12', '14']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
